name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js lts/*
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to npm
        run: yarn run release && cd packages/record && npm publish
        env:
          NPM_TOKEN: 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
